projet/news/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  get "reports/search" => "reports#search"
  get "sources/search" => "sources#search"
  post "users/:id/reset_password" => "users#reset_password"

  resources :media
  resources :categories
  resources :sources
  resources :reports
  resources :users
  
  
  root "reports#index"
  

end

projet/news/app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :reports
end

projet/news/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show, :search]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
	authorize! :manage, @category
  
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
	authorize! :manage, @category
  
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
	authorize! :manage, @category
  
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

projet/news/app/helpers/categories_helper.rb
module CategoriesHelper
end

projet/news/app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    Nom:<br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

projet/news/app/views/categories/edit.html.erb
<h1>Modifier une catégorie</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @category %> |
<%= link_to 'Retour', categories_path %>

projet/news/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Catégories</h1>

<% user_is_admin = user_signed_in? && current_user.role == "admin" %>

<table class="table">
  <thead>
    <tr>
      <th>Nom</th>
	  
	  <% if user_is_admin %>
		<th colspan="3">Actions</th>
	  <% end %>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr scope="row">
        <td><%= category.name %></td>
		
		<% if user_is_admin %>
			<td><%= link_to 'Afficher', category %></td>
			<td><%= link_to 'Modifier', edit_category_path(category) %></td>
			<td><%= link_to 'Supprimer', category, method: :delete, data: { confirm: 'Vraiment?' } %></td>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_is_admin %>
	<%= link_to 'Nouvelle catégorie', new_category_path %>
<% end %>

projet/news/app/views/categories/new.html.erb
<h1>Nouvelle catégorie</h1>

<%= render 'form' %>

<%= link_to 'Retour', categories_path %>

projet/news/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @category.name %>
</h1>

Dernières news de la catégorie <%= @category.name %> :
<ul>
	<% @category.reports.order("updated_at DESC").limit(30).each do |report| %>
		<li>
			<%= link_to report.title, report %> (<%= report.updated_at.to_formatted_s(:long_ordinal) %>)
		</li>
	<% end %>
</ul>

<% if user_signed_in? and current_user.role == "admin" %>
	<%= link_to 'Modifier', edit_category_path(@category) %> |
	<%= link_to 'Retour', categories_path %>
<% end %>