projet/news/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  get "reports/search" => "reports#search"
  get "sources/search" => "sources#search"
  post "users/:id/reset_password" => "users#reset_password"

  resources :media
  resources :categories
  resources :sources
  resources :reports
  resources :users
  
  
  root "reports#index"
  

end

projet/news/app/models/report.rb
class Report < ActiveRecord::Base
	has_and_belongs_to_many :categories
	has_and_belongs_to_many :sources
	belongs_to :user
	
	validates :title, presence: true
	validates :head, presence: true
	validates :text, presence: true
	
	validate :has_relations

	# Vérifie la présence d'au minimum une source et une catégorie à la news
	def has_relations
		errors.add(:base, 'Au minimum une source doit être liée') if self.sources.blank?
		errors.add(:base, 'Au minimum une catégorie doit être liée') if self.categories.blank?
	end
end

projet/news/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show, :search]
  
  # added
  def search
	@search_terms = params[:search_terms]
	@search_results = Hash.new
	@search_results["reports"] = Report.where("title LIKE ? OR head LIKE ? OR text LIKE ?", "%#{@search_terms}%", "%#{@search_terms}%", "%#{@search_terms}%").order("updated_at DESC").limit(20)
	@search_results["categories"] = Category.where("name LIKE ?", "%#{@search_terms}%")
	@search_results["sources"] = Source.where("firstname LIKE ? OR lastname LIKE ? OR name LIKE ?", "%#{@search_terms}%", "%#{@search_terms}%", "%#{@search_terms}%")
	@search_results["medias"] = Medium.where("name LIKE ?", "%#{@search_terms}%")
	
	render :partial => "reports_search"
  end
  
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.order(updated_at: :desc).limit(30)
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end
  
  # Assigne les catégories et sources correspondant à leurs ids reçus
  def assign_categories_and_sources
	# added
	parameters = report_params
	parameters[:user_id] = current_user.id
	
	# assignation des catégories
	categories = parameters[:categories]
	categories_obj = []

	if categories
		categories.each do |c|
			categories_obj << Category.find(c)
		end
	end
	
	parameters[:categories] = categories_obj

	# assignation des sources
	sources = parameters[:sources]
	sources_obj = []

	if sources
		sources.each do |s|
			sources_obj << Source.find(s)
		end
	end
	
	parameters[:sources] = sources_obj
	
	return parameters
  end

  # POST /reports
  # POST /reports.json
  def create
	if current_user.role != "author"
		redirect_to reports_path, notice: "Vous ne pouvez pas créer une news."
	else
		parameters = assign_categories_and_sources()

		# création de l'article
		@report = Report.new(parameters)

		respond_to do |format|
		  if @report.save
			format.html { redirect_to @report, notice: 'Report was successfully created.' }
			format.json { render :show, status: :created, location: @report }
		  else
			format.html { render :new }
			format.json { render json: @report.errors, status: :unprocessable_entity }
		  end
		end
	end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
	if @report.user.id != current_user.id
		redirect_to reports_path, notice: "Vous ne pouvez pas modifier cette news."
	else
		parameters = assign_categories_and_sources()

		respond_to do |format|
		  if @report.update(parameters)
			format.html { redirect_to @report, notice: 'Report was successfully updated.' }
			format.json { render :show, status: :ok, location: @report }
		  else
			format.html { render :edit }
			format.json { render json: @report.errors, status: :unprocessable_entity }
		  end
		end
	end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
	if @report.user.id != current_user.id && current_user.role != "admin"
		redirect_to reports_path, notice: "Vous ne pouvez pas modifier cette news."
	else
		@report.destroy
		respond_to do |format|
		  format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
		  format.json { head :no_content }
		end
	end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:title, :head, :text, :categories => [], :sources => [])
    end
end

projet/news/app/helpers/reports_helper.rb
module ReportsHelper
end

projet/news/app/views/reports/_form.html.erb
<h2>Ajouter des sources</h2>

<% @source = Source.new %>

<%= render 'sources/form' %>

<h2>Détails de la news</h2>

<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
	Catégories :<br>
	<ul>
    <% Category.all.each do |category| %>
		<li><div class="checkbox"><label><input type="checkbox" name="report[categories][]" value="<%= category.id %>" <%= 'checked="checked"' if @report.categories.include?(category) %> /><%= category.name %></div></label></li>
	<% end %>
	</ul>
  </div>
  
  <div class="form-group">
	Sources: <br>
	Rechercher: <input type="text" id="source_search_terms" class= "form-control" />
	<ul id="source_search_results">
	</ul>
	<ul id="source_list">
    <% @report.sources.each do |source| %>
		<li><div class="checkbox"><label><input type="checkbox" name="report[sources][]" value="<%= source.id %>" checked="checked" onchange="remove_source_from_report(this)" /><%= source.name %> <%= source.firstname %> <%= source.lastname %></div></label></li>
	<% end %>
	</ul>
  </div>

  <div class="form-group">
    Titre :<br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    Chapeau :<br>
	<%= f.text_area :head, class: "form-control" %>
  </div>
  <div class="form-group">
    Contenu: <br>
	<%= f.text_area :text, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

projet/news/app/views/reports/_reports_search.html.erb
<h3>
	Résultats pour: <%= @search_terms %>
</h3>

<h4>News</h4>
<ul>
	<% @search_results["reports"].each do |report| %>
		<li>
			<%= link_to report.title, report %> <%= report.updated_at.to_formatted_s(:long_ordinal) %>
		</li>
	<% end %>
</ul>

<h4>Catégories</h4>

<% if @search_results["categories"].length > 0 %>
	<ul>
		<% @search_results["categories"].each do |category| %>
			<li>
				<%= link_to category.name, category, class: "label label-default inlabel inlabel" %>
			</li>
		<% end %>
	</ul>
<% else %>
	<strong>Aucun résultat</strong>
<% end %>

<h4>Sources</h4>

<% if @search_results["sources"].length > 0 %>
	<ul>
		<% @search_results["sources"].each do |source| %>
			<li>
				<% if source.tyype == "PhysicalSource" %>
					<%= link_to source.firstname + " " + source.lastname, source, class: "label label-default inlabel" %>
				<% else %>
					<%= link_to source.name, source, class: "label label-default inlabel" %>
				<% end %>
				
			</li>
		<% end %>
	</ul>
<% else %>
	<strong>Aucun résultat</strong>
<% end %>

<h4>Médias</h4>

<% if @search_results["medias"].length > 0 %>
	<ul>
		<% @search_results["medias"].each do |media| %>
			<li>
				<%= link_to media.name, media %>
			</li>
		<% end %>
	</ul>
<% else %>
	<strong>Aucun résultat</strong>
<% end %>

projet/news/app/views/reports/edit.html.erb
<h1>Modifier une news</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @report %> |
<%= link_to 'Retour', reports_path %>

projet/news/app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>News</h1>

<div class="row">

	<% @reports.each do |report| %>

		<div class="col-md-4">
	
			<h3>
				<%= link_to report.title, report %>
			</h3>

			<div>
				<% if report.user != nil %>
					Par: <%= report.user.firstname %> <%= report.user.lastname %><br />
				<% end %>

				Dernière mise à jour: <%= report.updated_at.to_formatted_s(:long_ordinal) %>
			</div>

			<div>
				<%= report.head[0..50] %>
			</div>

			<% if user_signed_in? && current_user.id == report.user_id %>
				<%= link_to 'Modifier', edit_report_path(report) %>
				<%= link_to 'Supprimer', report, method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
		</div>

		
	<% end %>

</div>

<br>

<% if user_signed_in? && current_user.role == "author" %>
<%= link_to 'Nouvelle news', new_report_path %>
<% end %>

projet/news/app/views/reports/new.html.erb
<h1>Nouvelle news</h1>

<%= render 'form' %>

<%= link_to 'Retour', reports_path %>

projet/news/app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @report.title %>
</h2>

<div>
	<% if @report.user != nil %>
		Rédigé par: <%= @report.user.firstname %> <%= @report.user.lastname %><br />
	<% end %>

	Dernière mise à jour: <%= @report.updated_at.to_formatted_s(:long_ordinal) %><br />
	Catégorie(s):
	<% if @report.sources.size < 1 %>
		Aucune catégorie
	<% else %>
		<%  i = 0 %>
		<% @report.categories.each do |category| %>
			<a href="/categories/<%= category.id %>">
			<span class="label label-default">
			<%= category.name %>
			</span>
			</a>
			<% if i + 1 < @report.categories.size %>
				&nbsp;
			<% end %>
			<% i += 1 %>
		<% end %>
	<% end %>
	<br />
	Source(s):
	<% if @report.sources.size < 1 %>
		Aucune source
	<% else %>
		<%  i = 0 %>
		<% @report.sources.each do |source| %>
			<a href="/sources/<%= source.id %>">
			<span class="label label-default">
			<% if source.tyype == "PhysicalSource" %>
				<%= source.firstname %> <%= source.lastname %>
			<% else %>
				<%= source.name %>
			<% end %>
			</span>
			</a>
			<% if i + 1 < @report.sources.size %>
				&nbsp;
			<% end %>
			<% i += 1 %>
		<% end %>
	<% end %>
</div>

<div style="margin-top: 2em;">
	<h4>
		<%= @report.head %>
	</h4>
</div>

<p>
	<div>
	  <%= @report.text %>
	</div>
</p>

<% if user_signed_in? && current_user.id == @report.user_id %>
	<%= link_to 'Modifier', edit_report_path(@report) %> |
	<%= link_to 'Retour', reports_path %>
<% end %>