projet/news/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  get "reports/search" => "reports#search"
  get "sources/search" => "sources#search"
  post "users/:id/reset_password" => "users#reset_password"

  resources :media
  resources :categories
  resources :sources
  resources :reports
  resources :users
  
  
  root "reports#index"
  

end

projet/news/app/models/source.rb
class Source < ActiveRecord::Base
	has_and_belongs_to_many :reports
	
	validates :tyype, presence: true
	validates :firstname, presence: true, if: :isPhysicalSource?
	validates :firstname, length: { minimum: 3 }, if: :isPhysicalSource?
	validates :lastname, presence: true, if: :isPhysicalSource?
	validates :lastname, length: { minimum: 3 }, if: :isPhysicalSource?
	validates :name, presence: true, if: :isLogicalSource?
	validates :name, length: { minimum: 3 }, if: :isLogicalSource?
	
	def isPhysicalSource?
		:tyype == "PhysicalSource"
	end
	
	def isLogicalSource?
		:tyype == "LogicalSource"
	end

end

projet/news/app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show]

  def search
	@search_terms = params[:search_terms]
	@search_results = Source.where("firstname LIKE ? OR lastname LIKE ? OR name LIKE ?", "%#{@search_terms}%", "%#{@search_terms}%", "%#{@search_terms}%")
	
	# pour form
	@source = Source.new
	render :partial => "sources_search"
  end
  
  # GET /sources
  # GET /sources.json
  def index
    @sources = Source.all
  end

  # GET /sources/1
  # GET /sources/1.json
  def show
  end

  # GET /sources/new
  def new
    @source = Source.new
  end

  # GET /sources/1/edit
  def edit
  end

  # POST /sources
  # POST /sources.json
  def create
    @source = Source.new(source_params)
	authorize! :manage, @source

    respond_to do |format|
      if @source.save
		flash.now[:notice] = "La source a été créée."
       # format.html { redirect_to @source, notice: 'La source a été créée.' }
        #format.json { render :view, status: :created, location: @source }
        format.js { render :create, status: :created, location: @source }
      else
		flash.now[:error] = "La source n'a pas pu être créée.<br />" + @source.errors.full_messages.join("<br />")
        #format.html { render :new }
        #format.json { render json: @source.errors, status: :unprocessable_entity }
		#format.js { render :create, @source.errors, status: :unprocessable_entity }
		format.js { render :create, status: :created, location: @source }
      end
    end
  end

  # PATCH/PUT /sources/1
  # PATCH/PUT /sources/1.json
  def update
	authorize! :manage, @source
	
    respond_to do |format|
      if @source.update(source_params)
		flash.now[:notice] = "La source a été mise à jour."
        format.html { redirect_to @source, notice: 'La source a été mise à jour.' }
        format.json { render :show, status: :ok, location: @source }
      else
        format.html { render :edit }
        format.json { render json: @source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sources/1
  # DELETE /sources/1.json
  def destroy
	authorize! :manage, @source
  
    @source.destroy
    respond_to do |format|
      format.html { redirect_to sources_url, notice: 'La source a été supprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source
      @source = Source.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_params
      params.require(:source).permit(:tyype, :firstname, :lastname, :name)
    end
end

projet/news/app/helpers/sources_helper.rb
module SourcesHelper
end

projet/news/app/views/sources/_form.html.erb
<script type="text/javascript">
	function sourceTypeChanged(forceType) {
		var index = forceType != null ? forceType : document.getElementById('type').selectedIndex;

		document.getElementById("firstname").style.display = (index == 0 ? 'block' : 'none');
		document.getElementById("source_firstname").style.display = (index == 0 ? 'block' : 'none');
		document.getElementById("lastname").style.display = (index == 0 ? 'block' : 'none');
		document.getElementById("source_lastname").style.display = (index == 0 ? 'block' : 'none');
		document.getElementById("name").style.display = (index == 1 ? 'block' : 'none');
		document.getElementById("source_name").style.display = (index == 1 ? 'block' : 'none');
	}
</script>

<%= form_for(@source, remote: true) do |f| %>
  <% if @source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source.errors.count, "error") %> erreurs:</h2>

      <ul>
      <% @source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    Type:<br>
	<select name="source[tyype]" onchange="sourceTypeChanged(null)" id="type" class="form-control">
		<option value="PhysicalSource">Personne physique</option>
		<option value="LogicalSource">Autre entité</option>
	</select>
  </div>
  <div class="form-group" id="firstname">
   Prénom:<br>
    <%= f.text_field :firstname, class: "form-control" %>
  </div>
  <div class="form-group" id="lastname">
    Nom de famille:<br>
    <%= f.text_field :lastname, class: "form-control" %>
  </div>
  <div class="form-group" id="name">
    Nom:<br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

<script type="text/javascript">
<% if @source && !@source.new_record? %>
	sourceTypeChanged(<%= @source.tyype == "PhysicalSource" ? 0 : 1 %>);
<% else %>
	sourceTypeChanged();
<% end %>
</script>

projet/news/app/views/sources/_sources_search.html.erb
Sources trouvées pour: <%= @search_terms %>
<ul>
<% @search_results.each do |result| %>
	<li>
		<input type="button" class="btn btn-default" value="Ajouter" onclick="add_source_to_report(this, <%= result.id %>, '<%= result.firstname %> <%= result.lastname %> <%= result.name %>');"/>
		 <%= result.firstname %> <%= result.lastname %> <%= result.name %>
	</li>
<% end %>
</ul>

projet/news/app/views/sources/create.js.erb
$("#flash").html('<%= j render partial: "shared/notice_banner", :locals => {:notice => flash[:notice], :error => flash[:error]} %>');

if (add_source_to_report)
	add_source_to_report(null, <%=  @source.id %>, '<%=  @source.firstname %> <%=  @source.lastname %> <%=  @source.name %>');

projet/news/app/views/sources/edit.html.erb
<h1>Modifier une source</h1>

<%= render 'form' %>

<%= link_to 'Afficher', @source %> |
<%= link_to 'Retour', sources_path %>

projet/news/app/views/sources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sources</h1>

<table class="table">
  <thead>
    <tr>
      <th>Type</th>
	  
      <th>Prénom</th>
      <th>Nom</th>
      <th>Nom</th>
	   <% if user_signed_in? %>
		<th colspan="3">Actions</th>
	  <% else %>
		<th colspan="1">Actions</th>
	  <% end %>
    </tr>
  </thead>

  <tbody>
    <% @sources.each do |source| %>
      <tr scope="row">
        <td><%= (source.tyype == "PhysicalSource" ? "Personne Physique" : "Entité") %></td>
		
		<% if source.tyype == "PhysicalSource" %>
			<td><%= source.firstname %></td>
			<td><%= source.lastname %></td>
			<td></td>
		<% else %>
			<td></td>
			<td></td>
			<td><%= source.name %></td>
		<% end %>
		
		<td><%= link_to 'Afficher', source %></td>
		
		<% if user_signed_in? %>
			<td><%= link_to 'Modifier', edit_source_path(source) %></td>
			<td><%= link_to 'Supprimer', source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		 <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
	<%= link_to 'Nouvelle source', new_source_path %>
<% end %>

projet/news/app/views/sources/new.html.erb
<h1>Ajouter une source</h1>

<%= render 'form' %>

<%= link_to 'Retour', sources_path %>

projet/news/app/views/sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= (@source.tyype == "PhysicalSource" ? "Personne physique" : "Entité") %>
</p>

<% if @source.tyype == "PhysicalSource" %>
	<p>
	  <strong>Prénom:</strong>
	  <%= @source.firstname %>
	</p>

	<p>
	  <strong>Nom de famille:</strong>
	  <%= @source.lastname %>
	</p>
<% else %>
	<p>
	  <strong>Nom:</strong>
	  <%= @source.name %>
	</p>
<% end %>

<% if user_signed_in? %>
	<%= link_to 'Modifier', "/sources/#{@source.id}/edit" %> |
<% end %>

<%= link_to 'Retour', sources_path %>